# Generated by Django 3.2.6 on 2021-08-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftplogin',
            name='date',
            field=models.DateTimeField(null=True, unique=True, verbose_name='Date'),
        ),
    ]
