# Generated by Django 3.2.6 on 2021-08-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_api', '0002_alter_ftplogin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endlessh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, unique=True, verbose_name='Date')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('time_wasted', models.FloatField(null=True, verbose_name='Time_Wasted')),
                ('bytes_sent', models.IntegerField(null=True, verbose_name='Bytes_Sent')),
            ],
        ),
        migrations.RemoveField(
            model_name='ftplogin',
            name='username',
        ),
    ]
