# Generated by Django 3.2.6 on 2021-08-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
